name: NssNss
favicon: null
layout_spectrum: 0.3910454718861729
typography_spectrum: 0.5977102208416909
title: 'NssNss.ma '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050306'
    - '#2b2213'
    - '#544737'
    - '#8f7f68'
    - '#c5bcb7'
  brandStrength: 0.918165430193767
  lightness: 0.5554985338822007
  saturation: 0.8383591168094426
  rhythmicContrast: 0.2949862901587039
purpose: []
